apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hexagonal-template-postgresql
  labels:
    app: spring-hexagonal-template-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-hexagonal-template-postgresql
  template:
    metadata:
      labels:
        app: spring-hexagonal-template-postgresql
    spec:
      containers:
        - name: spring-hexagonal-template-postgresql
          image: postgres:16-alpine
          envFrom:
            - configMapRef:
                name: spring-hexagonal-template
            - secretRef:
                name: spring-hexagonal-template
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: spring-hexagonal-template-postgresql
  labels:
    app: spring-hexagonal-template-postgresql
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: spring-hexagonal-template-postgresql