apiVersion: v1
kind: Secret
metadata:
  name: spring-hexagonal-template
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME : cm9vdA==
  SPRING_DATASOURCE_PASSWORD : cGFzc3dvcmQ=
  POSTGRES_USER: cm9vdA==
  PGUSER: cm9vdA==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=